server:
  error:
    include-stacktrace: on_param
  max-http-request-header-size: 32KB
  max-http-form-post-size: 50MB
spring:
  application:
    name: Industrial Stock
  jackson:
    property-naming-strategy: SNAKE_CASE
  datasource:
    hikari:
      auto-commit: true
      minimum-idle: 3
      maximum-pool-size: 30
      idle-timeout: 30000
      transaction-isolation: TRANSACTION_READ_COMMITTED
  jpa:
    hibernate:
      ddl-auto: update
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
logging:
  level:
    org:
      hibernate:
        TransactionA: TRACE
    springframework:
      orm:
        jpa: DEBUG
      transaction: TRACE
      beans:
        factory: DEBUG
storage:
  basePath: /var/uploads
upload:
  sessionTtlHours: 24
